name: Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
defaults:
  run:
    working-directory: ./
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      - uses: npm/action-setup@v4
        with:
          version: 9.7.0
          run_install: |
            # - recursive: true
            # args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install
          npm build
      - name: Install playwright browsers
        run: |
          npm playwright install chromium --with-deps
          npm playwright install firefox --with-deps
          npm playwright install webkit --with-deps
          npm exec playwright install
      - name: Run tests
        run: npm test:coverage && npm test:e2e
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
